version: "3.8"

services:
  web:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    
    environment:
      - NODE_ENV=local 
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    healthcheck:
      test: curl -sSf http://localhost:8080 || exit 1 
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - redis  

  redis:
    image: redis:6.2
    restart: on-failure
    ports:
      - "6379:6379"

  zap:
    image: ghcr.io/zaproxy/zaproxy:2.15.0
    command: bash -c "zap.sh -cmd -addonupdate && zap.sh -cmd -autorun /zap/wrk/zap.yaml"
    volumes:
      - .:/zap/wrk
      - ./zap-working-dir:/home/zap/.ZAP
    depends_on:
      web:
        condition: service_healthy 
    environment:
      - ZAP_PORT=8080
    ports:
      - "8081:8080"

networks:
  default:
    name: lpa-validator-frontend
