asyncRequestApi: {
    url: https://pub-async.development.planning.data.gov.uk
}
aws: {
    region: eu-west-2,
    bucket: 'development-pub-async-request-files',
}
redis: {
    secure: false,
    host: 'localhost',
    port: 6379
}
url: 'http://localhost:5000/'
features:
  submitEndpointForm:
    enabled: true
