asyncRequestApi: {
    url: http://localhost:8000
}
aws: {
    region: eu-west-2,
    bucket: 'dluhc-data-platform-request-files-local',
    endpoint: 'http://localhost:4566',
    s3ForcePathStyle: true,
}
redis: {
    secure: false,
    host: 'localhost',
    port: 6379
}
port: 5000
url: 'http://localhost:5000/'
features:
  submitEndpointForm:
    enabled: true
